version: '3'

services:
  api:
    build: ./api
    container_name: api-matcha
    image: api-matcha
    command: go run main.go user.go
    volumes:
      - ./api/:/usr/src/api/
    ports:
        - 8080:8080
    environment:
      - SQL_USER=slerest
      - SQL_PASSWORD=secret
      - SQL_DATABASE=match
      - SQL_PORT=5432
    depends_on:
      - db
    networks:
      - fullstack
  db:
    image: postgres:12.0
    container_name: db-matcha
    environment:
      - POSTGRES_USER=slerest  
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=matcha
    ports:
        - 5432:5432
    volumes:
      - db_matcha:/var/lib/postgresql/data
    networks:
      - fullstack
volumes:
    api:
    db_matcha:
networks:
    fullstack:
      driver: bridge
